package com.godngu.excel.bulk.order.temp

/**
 * 에러코드.
 */
enum class ErrorCode(
    val code: String,
    val status: Int,
    val message: String
) {
    // 공통 오류
    BAD_REQUEST("ORDER_BACKOFFICE_COMMON_0000", 400, "서버가 요청 구문을 인식하지 못했습니다."),
    UNSUPPORTED_MEDIA_TYPE("ORDER_BACKOFFICE_COMMON_0001", 400, "지원하지 않는 미디어 타입입니다."),
    NOT_ACCEPTABLE("ORDER_BACKOFFICE_COMMON_0002", 400, "지원하지 않는 컨텐츠 타입입니다."),
    REQUEST_DATA_NOT_FOUND("ORDER_BACKOFFICE_COMMON_0003", 400, "요청값이 존재하지 않습니다."),
    FEIGN_CLIENT_REQUEST_FAIL("ORDER_BACKOFFICE_COMMON_0004", 400, "Feign Client 요청이 실패했습니다."),
    UNAUTHORIZED("ORDER_BACKOFFICE_COMMON_0005", 401, "인증이 필요합니다."),
    FORBIDDEN("ORDER_BACKOFFICE_COMMON_0006", 403, "권한이 없습니다."),
    ENTITY_NOT_FOUND("ORDER_BACKOFFICE_COMMON_0007", 404, "요청한 리소스를 찾을 수 없습니다."),
    REQUEST_MAPPING_NOT_FOUND("ORDER_BACKOFFICE_COMMON_0008", 404, "허용되지 않은 URL입니다."),
    INVALID_INPUT_VALUE("ORDER_BACKOFFICE_COMMON_0009", 422, "입력 값이 올바르지 않습니다."),
    INTERNAL_SERVER_ERROR("ORDER_BACKOFFICE_COMMON_0010", 500, "서버에 오류가 발생하여 요청을 수행하지 못했습니다."),
    GATEWAY_TIMEOUT("ORDER_BACKOFFICE_COMMON_0011", 504, "서버가 응답하지 않습니다."),
    BAD_EXCEL_DATA_FILE_NAME("ORDER_BACKOFFICE_COMMON_0012", 400, "파일명에 오류가 있습니다."),
    BAD_EXCEL_DATA_FILE_EXTENSION("ORDER_BACKOFFICE_COMMON_0013", 400, "파일 확장자가 xlsx가 아닙니다."),
    BAD_EXCEL_DATA("ORDER_BACKOFFICE_COMMON_0014", 400, "엑셀 양식에 값이 존재하지 않습니다."),
    BAD_EXCEL_DATA_MAX_ROW_SIZE("ORDER_BACKOFFICE_COMMON_0015", 400, "업로드는 200건 이하까지 가능합니다."),
    SEARCH_INPUT_KEYWORD_ERROR("ORDER_BACKOFFICE_COMMON_0016", 422, "키워드를 입력해 주세요."),

    ORDER_NOT_FOUND("ORDER_BACKOFFICE_ORDER_0000", 404, "개별주문번호가 유효하지 않습니다."),
    GROUP_ORDER_NOT_FOUND("ORDER_BACKOFFICE_GROUP_ORDER_0000", 404, "합 주문이 존재하지 않습니다."),
    BULK_ORDER_STATUS_CHANGE_UPLOAD_ORDER_NO_ERROR("BULK_ORDER_STATUS_CHANGE_UPLOAD_ORDER_NO_ERROR_0000", 4040, "엑셀 내 유효하지 않은 데이터가 있습니다. 수정 후, 다시 업로드 부탁드립니다."),

    REFUND_ORDER_NOT_FOUND("ORDER_BACKOFFICE_REFUND_ORDER_0000", 404, "환불 주문이 존재하지 않습니다."),
    EXIST_CREATED_REFUND_ORDER("ORDER_BACKOFFICE_REFUND_ORDER_0001", 400, "취소접수 중인 건이 있습니다. 이미 접수된 건이 취소철회/취소완료되어야 추가로 취소접수하실 수 있습니다."),
    EXIST_SUBMITTED_REFUND_ORDER("ORDER_BACKOFFICE_REFUND_ORDER_0002", 400, "환불 진행건이 존재합니다."),
    INVALID_REFUND_PRODUCT_QUANTITY("ORDER_BACKOFFICE_REFUND_ORDER_0003", 400, "환불 접수 하려는 상품 개수가 잘못되었습니다."),
    EXIST_ORDER_REFUND_RESTORE("ORDER_BACKOFFICE_REFUND_ORDER_0004", 400, "환불 복원건이 존재합니다."),
    NOT_EXIST_REFUND_PRODUCT_IN_ORDER_PRODUCT("ORDER_BACKOFFICE_REFUND_ORDER_0005", 400, "주문 상품 내역에 환불 접수 하려는 상품이 존재하지 않습니다."),
    INVALID_EXTRA_FEE("ORDER_BACKOFFICE_REFUND_ORDER_0006", 400, "환불 수수료 금액은 환불 금액보다 작아야합니다."),
    CREATED_REFUND_ORDER_NOT_FOUND("ORDER_BACKOFFICE_REFUND_ORDER_0007", 400, "환불 주문 접수건이 존재하지 않습니다."),
    SUBMITTED_REFUND_ORDER_NOT_FOUND("ORDER_BACKOFFICE_REFUND_ORDER_0008", 400, "환불 주문 진행건이 존재하지 않습니다."),
    EXIST_ORDER_REFUND_PRODUCT_RESTORE("ORDER_BACKOFFICE_REFUND_ORDER_0009", 400, "환불 상품 복원건이 존재합니다."),
    INVALID_COUPON_CODE("ORDER_BACKOFFICE_REFUND_ORDER_0010", 400, "존재하지 않은 쿠폰 코드로 쿠폰 회수할 수 없습니다."),
    INVALID_MEMBER_NO("ORDER_BACKOFFICE_REFUND_ORDER_0011", 400, "회원번호가 존재하지 않습니다."),
    INVALID_MOBILIANS_REFUND_ORDER("ORDER_BACKOFFICE_REFUND_ORDER_0012", 400, "모빌리언스 주문건은 익월 환불이 불가능합니다."),
    NOT_EXIST_BANK_CODE("ORDER_BACKOFFICE_REFUND_ORDER_0013", 400, "환불은행코드가 존재하지 않습니다."),
    INVALID_REFUND_PRODUCT("ORDER_BACKOFFICE_REFUND_ORDER_0014", 400, "한불 접수 하려는 상품이 잘못되었습니다."),
    BULK_PARTIAL_REFUND_EXECUTE_ERROR("BULK_PARTIAL_REFUND_EXECUTE_ERROR", 400, "대량 부분 취소 환불은 한번만 진행할 수 있습니다."),

    POINT_CLIENT_REQUEST_FAIL("ORDER_BACKOFFICE_POINT_API_ERROR_0001", 400, "Point-api 요청이 실패했습니다."),
    COMMERCE_MESSAGE_CLIENT_REQUEST_FAIL("ORDER_BACKOFFICE_COMMERCE_MESSAGE_API_ERROR_0001", 400, "Commerce-message-api 요청이 실패했습니다."),
    PAYMENT_CANCEL_AGENT_CLIENT_REQUEST_FAIL("ORDER_BACKOFFICE_PAYMENT_CANCEL_AGENT_ERROR_0001", 400, "Payment-cancel-agent 요청이 실패했습니다."),
    PAYMENT_CANCEL_AGENT_JOB_FAIL("ORDER_BACKOFFICE_PAYMENT_CANCEL_AGENT_ERROR_0002", 400, "Payment-cancel-agent Job 실패했습니다."),
    PAYMENT_CANCEL_AGENT_PAYMENT_CANCEL_FAIL("ORDER_BACKOFFICE_PAYMENT_CANCEL_AGENT_ERROR_0003", 400, "Payment-cancel-agent 결제 실패했습니다."),

    PREVIOUS_ORDER_STATUS_CHANGE("ORDER_BACKOFFICE_ORDER_STATUS_0000", 400, "주문상태 변경에 실패했습니다. 다시 시도해주세요."),
    OVER_STEP_ORDER_STATUS_CHANGE("ORDER_BACKOFFICE_ORDER_STATUS_0001", 400, "주문상태는 순서대로 변경 가능합니다."),
    NOT_1P_ORDER_STATUS_CHANGE("ORDER_BACKOFFICE_ORDER_STATUS_0003", 400, "1P 주문 상태변경은 불가 합니다."),
    PAYMENT_NOT_MADE_ERROR("ORDER_BACKOFFICE_ORDER_STATUS_0004", 400, "주문상태 변경에 실패했습니다. 다시 시도해주세요."),
    DELIVERY_NOT_COMPLETED("ORDER_BACKOFFICE_ORDER_STATUS_0005", 400, "배송 완료가 되지 않은 주문입니다."),
    ALL_PRODUCTS_ARE_REFUNDED("ORDER_BACKOFFICE_ORDER_STATUS_006", 400, "모든 주문이 취소되어 주문상태를 변경할 수 없습니다."),

    MISSING_PRODUCTION_LOG_NOT_FOUND("ORDER_BACKOFFICE_MISSING_PRODUCTION_LOG_0000", 404, "미출 등록 로그가 존재하지 않습니다."),
    VERIFICATION_MISSING_PRODUCTION_ORDER_NO_ERROR("ORDER_BACKOFFICE_MISSING_PRODUCTION_LOG_0001", 400, "주문 번호 정보가 조건에 충족하지 않습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_GROUP_ORDER_NO_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0001", 404, "대표주문번호가 유효하지 않습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_ORDER_TYPE_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0002", 404, "대량부분취소 불가능한 주문 유형입니다."),
    BULK_PARTIAL_REFUND_VALIDATE_ORDER_DEAL_CODE_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0003", 404, "딜코드가 유효하지 않습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_ORDER_MASTER_CODE_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0004", 404, "마스터코드가 유효하지 않습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_ORDER_QUANTITY_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0005", 404, "수량이 유효하지 않습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_ORDER_REFUND_TYPE_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0006", 404, "취소사유코드가 유효하지 않습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_MEMO_LENGTH_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0007", 404, "메모가 20자를 초과하였습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_MEMO_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0008", 404, "메모에 유효하지 않은 문자가 포함되어 있습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_CHECK_REFUND_COMPLATE_BY_GROUP_NO_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0009", 404, "이미 취소완료된 대표주문번호입니다."),
    BULK_PARTIAL_REFUND_VALIDATE_REFUND_STATUS_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0010", 404, "이미 취소접수/취소완료된 상품입니다."),
    BULK_PARTIAL_REFUND_VALIDATE_REFUND_UPLOAD_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0011", 404, "대량부분취소 업로드 데이터가 존재하지 않습니다."),
    BULK_PARTIAL_REFUND_VALIDATE_ORDER_STATUS_ERROR("BULK_PARTIAL_REFUND_VALIDATE_ERROR_0012", 404, "주문시도 상태의 주문은 취소할 수 없습니다.");

    companion object {
        /**
         * Http Status Code에 알맞은 공통 오류 코드 객체 code 값을 리턴.
         *
         * @param httpStatusCode Http Status Code
         * @return 공통 오류 코드 객체 code 값
         * */
        fun of(httpStatusCode: Int): ErrorCode {
            return when (httpStatusCode) {
                400 -> BAD_REQUEST
                401 -> UNAUTHORIZED
                403 -> FORBIDDEN
                404 -> ENTITY_NOT_FOUND
                406 -> NOT_ACCEPTABLE
                415 -> UNSUPPORTED_MEDIA_TYPE
                422 -> INVALID_INPUT_VALUE
                500 -> INTERNAL_SERVER_ERROR
                504 -> GATEWAY_TIMEOUT
                else -> INTERNAL_SERVER_ERROR
            }
        }
    }
}
